// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlc64kDGaTAckSX05-W7mBDZUbK9o4jqc',
    appId: '1:288120263683:web:3038d73df31d2503c82a36',
    messagingSenderId: '288120263683',
    projectId: 'stacked-techidara-1',
    authDomain: 'stacked-techidara-1.firebaseapp.com',
    storageBucket: 'stacked-techidara-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBew7W__z_DQI8pWgC5QLwX5sTXUcUMrk8',
    appId: '1:288120263683:android:8d62dce50a013c37c82a36',
    messagingSenderId: '288120263683',
    projectId: 'stacked-techidara-1',
    storageBucket: 'stacked-techidara-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgxBJMaxIfWdS7LgdaRlxxE2Rd3E8wJHQ',
    appId: '1:288120263683:ios:038a38d5433d1ec4c82a36',
    messagingSenderId: '288120263683',
    projectId: 'stacked-techidara-1',
    storageBucket: 'stacked-techidara-1.appspot.com',
    iosClientId: '288120263683-vghrac56iaqoua4jutoq0o6id4vjjof1.apps.googleusercontent.com',
    iosBundleId: 'com.example.stackedExplained',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgxBJMaxIfWdS7LgdaRlxxE2Rd3E8wJHQ',
    appId: '1:288120263683:ios:038a38d5433d1ec4c82a36',
    messagingSenderId: '288120263683',
    projectId: 'stacked-techidara-1',
    storageBucket: 'stacked-techidara-1.appspot.com',
    iosClientId: '288120263683-vghrac56iaqoua4jutoq0o6id4vjjof1.apps.googleusercontent.com',
    iosBundleId: 'com.example.stackedExplained',
  );
}
