// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXtrM8_1lv38k8UVv6Jv8gdlmc5Lobek0',
    appId: '1:276666989172:web:9ac22a2b46ff21492c2f21',
    messagingSenderId: '276666989172',
    projectId: 'fire-app-demo-one',
    authDomain: 'fire-app-demo-one.firebaseapp.com',
    storageBucket: 'fire-app-demo-one.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJhRfUyFOj63L1yVHABUTmfcwvXLVfBJY',
    appId: '1:276666989172:android:e3429152a32f6f0d2c2f21',
    messagingSenderId: '276666989172',
    projectId: 'fire-app-demo-one',
    storageBucket: 'fire-app-demo-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT17GrvmS_r9aFcNCHc30AlvLmkcc3sdw',
    appId: '1:276666989172:ios:8acdff393c9930e62c2f21',
    messagingSenderId: '276666989172',
    projectId: 'fire-app-demo-one',
    storageBucket: 'fire-app-demo-one.appspot.com',
    iosClientId: '276666989172-rbuqporc42ten1m3ukie7c77q9oj6d2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireAppDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT17GrvmS_r9aFcNCHc30AlvLmkcc3sdw',
    appId: '1:276666989172:ios:8acdff393c9930e62c2f21',
    messagingSenderId: '276666989172',
    projectId: 'fire-app-demo-one',
    storageBucket: 'fire-app-demo-one.appspot.com',
    iosClientId: '276666989172-rbuqporc42ten1m3ukie7c77q9oj6d2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireAppDemo',
  );
}
